service: freework

frameworkVersion: '3'

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1

package:
  artifact: target/freework-dev.jar

functions:
  cadastrarUsuario:
    handler: com.freework.handler.CadastroUsuarioHandler
    timeout: 60 #seconds

  autenticarUsuario:
    handler: com.freework.handler.AutenticarUsuarioHandler
    timeout: 60

  buscarFornecedores:
    handler: com.freework.handler.buscarFornecedoresHandler
    timeout: 60