service: FreeWork

frameworkVersion: '3'

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: com.freework.Handler
    timeout: 60 #seconds
    memorySize: 128 #mb

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
