service: freework

frameworkVersion: '3'

provider:
  name: aws
  runtime: java8
  stage: prd
  region: us-east-1

package:
  artifact: target/freework-prd.jar

functions:
  hello:
    handler: com.freework.handler.CadastroUsuarioHandler
    timeout: 60 #seconds