AWSTemplateFormatVersion: "2010-09-09"
Resources:
  tabelaDeUsuarios:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "usuarios"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "emailIndex"
          KeySchema:
            - AttributeName: "email"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  tabelaDePrestadores:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "companhias"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "category"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: "categoryIndex"
          KeySchema:
            - AttributeName: "category"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  
  tabelaDeServicosContratados:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: "contratacoes"
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "N"
      - AttributeName: "email"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    GlobalSecondaryIndexes:
      - IndexName: "emailIndex"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"